USE [master]
GO

/****** Object:  Database [geo]    Script Date: 12/12/2018 22:20:40 ******/
CREATE DATABASE [geo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'geo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\geo.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'geo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\geo_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [geo] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [geo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [geo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [geo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [geo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [geo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [geo] SET ARITHABORT OFF 
GO

ALTER DATABASE [geo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [geo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [geo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [geo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [geo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [geo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [geo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [geo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [geo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [geo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [geo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [geo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [geo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [geo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [geo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [geo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [geo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [geo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [geo] SET  MULTI_USER 
GO

ALTER DATABASE [geo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [geo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [geo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [geo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [geo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [geo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [geo] SET  READ_WRITE 
GO


